name: algolia-uploader

on: 
  - push

jobs:
  upload_algolia_index:
    runs-on: ubuntu-latest
    name: Upload Algolia Index
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip
        python3 -m pip install --upgrade pip
        pip3 install algoliasearch==2.0.0
        pip install algoliasearch==2.0.0
    - uses: guzhongren/algolia-docsearch-upload-action@v2.0.0
      with:
        # Such as `Z0U0ACGBN8`
        APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}

        # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ALGOLIA_ADMIN_KEY }}

        ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        # The index name. 
        INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
        # The index file path relative to repo root.

        FILE_PATH: ./index.json
