on: 
  - push

jobs:
  upload_algolia_index:
    runs-on: ubuntu-latest
    name: Upload Algolia Index
    steps:
    - uses: algolia/setup-algolia-cli@master
    - name: Import settings
    run: algolia settings import ${{ ALGOLIA_INDEX_NAME }} -F ./index.json
    env:
      ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
