name: algolia-uploader

on: 
  - push

jobs:
  upload_algolia_index:
    runs-on: ubuntu-latest
    name: Upload Algolia Index
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: wangchucheng/algolia-uploader@master
      with:
        # Such as `Z0U0ACGBN8`
        app_id: ${{ secrets.ALGOLIA_APP_ID }}

        # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ALGOLIA_ADMIN_KEY }}

        admin_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        # The index name. 
        index_name: ${{ secrets.ALGOLIA_INDEX_NAME }}
        # The index file path relative to repo root.

        index_file_path: ./index.json
